-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dob" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "gender" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "image" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "userName" TEXT NOT NULL DEFAULT '';
